[project]
name = 'delegato-cont'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Voting-proposal]
path = 'contracts/Voting-proposal.clar'
clarity_version = 1
epoch = 2.05

[contracts.proxy-governance]
path = 'contracts/proxy-governance.clar'
clarity_version = 3
epoch = 3.0

[contracts.proxy-management]
path = 'contracts/proxy-management.clar'
clarity_version = 1
epoch = 2.05

[contracts.proxy-voting]
path = 'contracts/proxy-voting.clar'
clarity_version = 3
epoch = 3.0

[contracts.shareholder-registration]
path = 'contracts/shareholder-registration.clar'
clarity_version = 3
epoch = 3.0

[contracts.vote-delegation]
path = 'contracts/vote-delegation.clar'
clarity_version = 3
epoch = 3.0

[contracts.voting-rights]
path = 'contracts/voting-rights.clar'
clarity_version = 3
epoch = 3.0

[contracts.voting-security]
path = 'contracts/voting-security.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
